### ISSUE TITLE
Generate poster img in Full HD resolution

### ISSUE THREAD

**Issue by saerdnaer** [voc/publishing#10]
probably in https://github.com/voc/publishing/blob/dev-andi/postprocessing/generate_thumb_autoselect_compatible.sh#L37

**Comment by MaZderMind** [comment]
@dedeibel is working on that, afaict

**Comment by dedeibel** [comment]
Yes, the solution is related to a voctoweb issue https://github.com/voc/voctoweb/issues/117

**Comment by derpeter** [comment]
@dedeibel @MaZderMind so shall i change things here or are you going to do it in voctoweb? Let me know what works best for you

**Comment by dedeibel** [comment]
In my opinion both repos are affected. I am unsure how you are usually handling this. My approach would be to link them, handle repo specific discussions in the affected ticket and close them once it is fixed fully.

One part is modifying the post processing script, the other is regenerating the images and modify voctoweb to handle them.

**Comment by dedeibel** [comment]
I asked myself why ffmpeg is used to create the thumbnail images from png to jpg instead of ImageMagick. In my view the result of ImageMagick was more clear than the ffmpeg version with similar size. Any opinion on that?
(already increased resolution to 400x)

```
 26K c117_java_-_2013-08-24_11_15_-_praktischer_einstieg_in_die_android-entwicklung_-_mag_hoehme_-_1252_im.jpg
 25K c117_java_-_2013-08-24_11_15_-_praktischer_einstieg_in_die_android-entwicklung_-_mag_hoehme_-_1252.jpg
```

ffmpeg

![c117_java_-_2013-08-24_11_15_-_praktischer_einstieg_in_die_android-entwicklung_-_mag_hoehme_-_1252](https://cloud.githubusercontent.com/assets/26708/20852073/1cf66098-b8e4-11e6-9107-65696f11da77.jpg)

ImageMagick

![c117_java_-_2013-08-24_11_15_-_praktischer_einstieg_in_die_android-entwicklung_-_mag_hoehme_-_1252_im](https://cloud.githubusercontent.com/assets/26708/20852072/1cf5ea50-b8e4-11e6-9d14-cc63bf6ad806.jpg)

**Comment by MaZderMind** [comment]
I think there is no real reason for ffmpeg being used here besides the obvious "because it can do everything" ;). If the results are better, we should use IM or GM here.

**Comment by dedeibel** [comment]
Results from IM and GM seem to be equal in this case, I would like to go with GM then because of it's postulated performance and memory footprint advantages.

**Comment by derpeter** [comment]
@dedeibel i merged your ffmpeg based changes to the dev git. ffmpeg is available on all our boxes and i would like to keep the deps smal. On the other hand i agree with @MaZderMind on the quality aspect. 
The pyhton way would be using cv2 i guess.

**Comment by MaZderMind** [comment]
The script just runs on live.ber and installing gm there is done in minutes. Gm is also available in nearly all repos of all OSes I know of, so I don't really see a Point in avoiding this dependency, if it raises the results quality ;)

**Comment by dedeibel** [comment]
Imho this particular dependency should not be a problem - but we are talking about a 400px image, we should not stretch too far for this. The full size preview image was not affected.

I would press the issue if there would be an ansible profile for the machine performing this task and a adding the dep would be a single line fix.

**Comment by derpeter** [comment]
@MaZderMind we want to move it away from live but thats another topic. 
@dedeibel can you provide your GM lines ?

**Comment by dedeibel** [comment]
@derpeter https://github.com/dedeibel/publishing/commit/b7d2481d9d65aa9666d0eedaa23bdd3e5150c382

**Comment by jjeising** [comment]
Have you tried changing `-q:v` for comparison?

**Comment by dedeibel** [comment]
Yes, -q:v 0 is already the best setting iirc - it just gets worse from there.

**Comment by dedeibel** [comment]
I seems like the filter configuration `-filter_complex:v 'scale=400:-1:lanczos' ` using the lanczos scaling algorithm seems to deliver a result, comparable to gm.

Strangely the documentation and the googles tells to set the parameter as `-sws_flags lanczos` https://www.mankier.com/1/ffmpeg-scaler

**Comment by derpeter** [comment]
any updates on this?

**Comment by derpeter** [comment]
we now generate high res images
