### ISSUE TITLE
Mehr als zwei Sprachen unterstützen

### ISSUE THREAD

**Issue by saerdnaer** [voc/publishing#11]
Aktuell sind zwei Sprachen hartcodiert im Code. Da wir beim 33C3 auch offiziell mehr als eine Übersetzerspur unterstützen, würde ich vorschlagen den folgenden Codeblock von extra Variablen pro Sprache auf eine Schleife umzustellen:
https://github.com/voc/publishing/blob/dev-andi/script_H_publishing.py#L189-L219

**Comment by derpeter** [comment]
Seid nem halben jahr im code 
https://github.com/voc/publishing/blob/refactor/script_H_media_ccc_upload.py#L239
