### ISSUE TITLE
Einzelsprachen MP4's nicht doppelt demuxen sondern Dateien recyclen

### ISSUE THREAD

**Issue by saerdnaer** [voc/publishing#12]
Aus dem Tracker fällt ein MP4 mit mehren Audiospuren. Für Youtube und für den voctoweb-Workaround brauchen wir aber auch MP4's mit nur einer Audiospur.  Aus historischen Gründen wird das aktuell zwei mal gemacht: einmal für YouTube und einmal für Media. Aus meiner Sicht sollten wir das vereinheitlichen und die selben Dateien dafür benutzen.

**Comment by derpeter** [comment]
Eher low prio da das quasi nix kostet, ich muss mir dazu ansehen wie viel man in der youtube klasse anpassen muss. Das ist bis her getrennt gewesen da ich diese eben nicht anfassen wollte.

**Comment by derpeter** [comment]
Da wir das muxen für single audio auf dauer raus werfen lohnt der aufwand nicht den context zu halten
