### ISSUE TITLE
Neue Version der YouTube-API Klasse nach Master mergen

### ISSUE THREAD

**Issue by saerdnaer** [voc/publishing#13]
Seit dem EMF Camp und bei der Subscribe8 hab ich die Youtube Klasse um ein paar Funktionen erweitert: Man kann jetzt auch einfach aus dem Code Playlists anlegen oder Thumbnails updaten. 
Vorschlag alle youtube-* Dateien in den Master-Branch übernehmen und den restlichen Code so anzupassen das er mit den neuen Youtube-Klasse (youtube-client.py) funktioniert.

**Comment by derpeter** [comment]
wie gesagt hab ich was die youtube klasse angeht kein ownership kann somit gerne unabhängig vom rest gemerged werden wenn die tut.

**Comment by derpeter** [comment]
fixed with 20f52799131905a876c70ea5d4b2a13216e53f4e
