### ISSUE TITLE
add md5check of files bevor upload to prevent reuploads of identical files

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#2]

**Comment by MaZderMind** [comment]
you could just call rsync with --checksum, instead of doing the transfer with paramiko.

**Comment by derpeter** [comment]
i would rather to that as i god much less control of the process from inside pyhton by calling a 
shell for rasync than handling things in paramiko.

**Comment by derpeter** [comment]
after changes in the code this only happens on rereleases and there should be no duplicat.
Also the rereleasing adressed in other issues will make this obsolet
