### ISSUE TITLE
Show recordings only if videos are uploaded

### ISSUE THREAD

**Issue by dedeibel** [voc/publishing#20]
It can happen that events and links to recordings are listed on media.ccc.de but no recording files are present. The player is not working and files will 404.
People will notice this as a bug and lose confidence in the app.

According to mazdermind and atze we could use the state field to control visibility of events until the files are uploaded.

**Comment by derpeter** [comment]
we upload the files bevor we create the event. if there is a 404 it is a cdn error

**Comment by MaZderMind** [comment]
That might be correlated with voc/voctoweb#186.
@dedeibel have you seen this happening with regular files or just with torrents?

**Comment by derpeter** [comment]
maybe but i still don't see the connection to the publishing
