### ISSUE TITLE
Youtube titles are broken for single language talks

### ISSUE THREAD

**Issue by jjeising** [voc/publishing#21]
See https://www.youtube.com/watch?v=oV_xKDB-mdA and Talk 373 in `33c3-sz`.

**Comment by derpeter** [comment]
fixed in 67d13f16dfd1f208eb692bf92b5c8910fce2e8c1

**Comment by saerdnaer** [comment]
This fix still adds an - deu or - eng  for single language releases: I would suggest to remove the whole else block in lines 178-179

**Comment by saerdnaer** [comment]
Was probably fixed by #33
