### ISSUE TITLE
Event link might be wrong if not using frab exported fahrplans

### ISSUE THREAD

**Issue by manno** [voc/publishing#25]
Voctoweb guesses the events url as follows:
https://github.com/voc/voctoweb/blob/master/app/models/concerns/fahrplan_updater.rb#L18

Does publishing set the link directly via the API? If it does, https://github.com/voc/voctoweb/blob/master/app/controllers/api/events_controller.rb#L87 should never overwrite params from the same request.

**Comment by derpeter** [comment]
See https://github.com/voc/publishing/issues/23 . we don't do it right no but its an issue here.

I agree media should not override things that come from the API.

**Comment by derpeter** [comment]
i assume this is closed by the changes in voctoweb
