### ISSUE TITLE
youtube client needs more verbose error reporting

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#31]
A 503 from youtube results in 

uploading video failed with error-code 503: {
 "error": {
  "errors": [
   {
    "domain": "global",
    "reason": "backendError",
    "message": "Backend Error"
   }
  ],
  "code": 503,
  "message": "Backend Error"
 }
}

this needs more infos to be usable

**Comment by saerdnaer** [comment]
In which cases does such an error message appear?

**Comment by derpeter** [comment]
turns out youtube dont gives us more information so wont fix
