### ISSUE TITLE
missing fahrplan.slug (and maybe other properties) resulting in open ticket not in an failed one

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#37]

**Comment by derpeter** [comment]
https://github.com/derpeter/publishing/commit/b07e750e11a077348533c3984dd102b754482d6f

**Comment by derpeter** [comment]
quatsch fixt das garnicht

**Comment by derpeter** [comment]
https://github.com/derpeter/publishing/commit/115cc3a98525ba2550c74cd31ed7bc853ec76687

**Comment by a-tze** [comment]
I'm confused.. you didnt merge that, right? Maybe the issue should stay open and have a certain label or something, just to not loose track.
