### ISSUE TITLE
new format for youtube titles

### ISSUE THREAD

**Issue by saerdnaer** [voc/publishing#4]
möglicher Vorschlag:
Conference: Titel (Vortragener 1, Vortragender 2)

Alternativ: mit Suffix und Prefix arbeitern, oder gleich mit nem Templates, sprich ein String in dem man über $variable den entsprechenden Wert einfügen kann.

**Comment by derpeter** [comment]
Is this issue still existing in the new youtube class?

**Comment by derpeter** [comment]
no comments in 6 days. please open new issue if problem still exists
