### ISSUE TITLE
Translated videos are not uploaded with the language as tag

### ISSUE THREAD

**Issue by dedeibel** [voc/publishing#43]
It would be nice for bigger conferences like the congress with multiple translations and a lot of talks to have playlists for each language. As a viewer on a mobile device it becomes really hard to find the desired video especially since we append the language at the end of the video title.

I think there should be a playlist for all languages and one with the original recordings.

[33c3 Playlists (youtube)](https://www.youtube.com/results?sp=EgIQA1AU&search_query=Chaos+Communication+Congress+2016)

For 33c3 I sorted them using a script afterwards but there should be an easier way, we could create the playlists in advance and auto-add the video according to the tag for the conference in combination with a tag for the language. e.g "34c3 German" and "34c3 OV". If youtube can't search for multiple tags in this feature we might use s.th. like "34c3_OV" I guess. [youtube auto-add-playlist screenshot](https://user-images.githubusercontent.com/26708/32519264-747df95a-c40c-11e7-9769-aa3a0c573923.png)

It seems like the is already code that can do something similar but the uploaded videos do not have the tags. 

One Example: ![youtube-tags](https://user-images.githubusercontent.com/26708/32519185-36105e9c-c40c-11e7-98b3-ed9f44dd11b8.png)

Additionally the "OV" feature is missing and the tag of translated versions is a bit verbose. Youtube Client Tag code: [youtube_client.py#L377](https://github.com/voc/publishing/blob/master/src/api_client/youtube_client.py#L377)

There are only the tracker configured tags present:

![33c3tracker](https://user-images.githubusercontent.com/26708/32519310-9d709386-c40c-11e7-947b-73209c02cc97.png)

**Comment by dedeibel** [comment]
To wrap it up:

Conference tag as example: "34c3"

- All videos should have the conference slug as tag ``"34c3"``
- All videos should **additionally** have their language as tag ``"34c3 ger"``
- Non translated videos should **additionally** have the tag ``"34c3 OV"``

A video, originally in german with an english translation would result in:

- German Video → ``"34c3", "34c3 OV", "34c3 ger"``
- Translated English Video → ``"34c3", "34c3 eng"``

_The repeating "34c3" slug is added since I am not exactly sure if you can add multiple tags and they are treated as AND condition._

**Comment by dedeibel** [comment]
According to the youtube doc the white space in the tag should be fine, but if this is a headache underscore is totally fine.

**Comment by derpeter** [comment]
![screenshot from 2017-12-25 21-52-43](https://user-images.githubusercontent.com/599344/34342856-fb55ee02-e9bd-11e7-838b-ddff1960b966.png)
![screenshot from 2017-12-25 21-52-19](https://user-images.githubusercontent.com/599344/34342857-fbc094c8-e9bd-11e7-992c-fc750464d91a.png)
@dedeibel  is this the intendet result (conference slug is "test" in the screenshots)

**Comment by derpeter** [comment]
this is closed since 34c3
