### ISSUE TITLE
Implement Slide-Only releases

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#47]
- master release contains 2. video track. Nothing to do here
  - figure out what needs to be done on vocotoweb code 
- remux a slide only video from master that contains only the slide video track an the native audio track
- do the remuxing for h264 HD / webm HD, also for SD?
- figure out what needs to be done on vocotweb to show these files

**Comment by a-tze** [comment]
There should be some kind of information wether the master contain the slide video track at all. Either have some property in the tickets or do ffprobe?
Doing the remuxing for webm or SD seems a bit explosive to the number of formats. But that also interacts with voctoweb's capabilities. If those versions are not presented in the player, they are unneeded or just political...

**Comment by MaZderMind** [comment]
I'd suggest adding a Tracker Project-Property and deciding based on that.

**Comment by derpeter** [comment]
the file is now generated by a tracker profile. Now we need to define how media should handle the file / how we tell media about the file

**Comment by derpeter** [comment]
@manno any thoughts on this?

**Comment by derpeter** [comment]
implemented in 34c3 release
