### ISSUE TITLE
add trim to all paths that come from the tracker

### ISSUE THREAD

**Issue by derpeter** [voc/publishing#5]
Prevent broken paths by trimming the input

**Comment by a-tze** [comment]
To be exact, it was not a path but the host property.
+1

**Comment by saerdnaer** [comment]
Side note: I would recommend to use os.path.join([pathpart1, pathpart2]) instead of pathpart1 + "/" + pathpart2

**Comment by derpeter** [comment]
thx for the comment. all pathes shoud use join now
